name: linux

on:
  push:

jobs:

  build-linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1
    - name: Install ZeroMQ
      run: |
        sudo add-apt-repository ppa:chris-lea/zeromq
        sudo apt-get update
        sudo apt-get install libzmq3-dbg libzmq3-dev libzmq3
    - name: setup
      run: |
        export CC=gcc-8
        export CXX=g++-8
        cd ..
        git clone https://github.com/open-ephys/plugin-GUI.git
        cd plugin-GUI/Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        cd ../Resources/Scripts
        sudo ./install_linux_dependencies.sh
    - name: build
      run: |
        cd Build
        export CPLUS_INCLUDE_PATH=/usr/local/hdf5/include
        export LIBRARY_PATH=/usr/local/hdf5/lib
        export LD_LIBRARY_PATH=/usr/local/hdf5/lib
        export CC=gcc-8
        export CXX=g++-8
        export PATH=$PATH:/usr/local/hdf5/include:/usr/local/hdf5/lib
        export 
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        make
#    - name: test
#      run: cd build && ctest
    - name: deploy
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
        build_dir: "Build"
        repo: ${{ github.event.repository.name }}
        package: ${{ github.event.repository.name }}-linux
      run: |
        plugin_api=$(grep -rnw ../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]*" | tail -1)
        tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        new_plugin_ver=$tag-API$plugin_api
        mkdir plugins
        if [[ $(ls $build_dir/*/*.so) ]]; then
            cp -r $build_dir/*/*.so plugins
        else
            cp -r $build_dir/*.so plugins
        fi
        zipfile=${package}_${new_plugin_ver}.zip
        zip -r -X $zipfile plugins
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/$bintrayUser/$repo/$package/$new_plugin_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/$bintrayUser/$repo/$package/$new_plugin_ver/publish